name: KaneAI Tests on Localhost via Tunnel

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-kaneai-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Start Vite Dev Server
        run: npm run dev &
        env:
          CI: true

      - name: 📡 Start LambdaTest Tunnel
        run: |
          curl -O https://downloads.lambdatest.com/tunnel/v3/linux/lambdatest-tunnel.zip
          unzip lambdatest-tunnel.zip
          chmod +x lambdatest-tunnel
          
          ./lambdatest-tunnel \
            --user ${{ secrets.LT_USERNAME }} \
            --key ${{ secrets.LT_ACCESS_KEY }} \
            --tunnelName kaneai-local \
            --infoAPI > tunnel.log &
          
          echo "Waiting for tunnel to stabilize..."
          sleep 25

      - name: 🚦 Wait for Vite App
        run: |
          for i in {1..20}; do
            curl -s http://localhost:5173 && echo "App is live" && break
            echo "Waiting for Vite app to be ready..."
            sleep 3
          done

      - name: 🧪 Trigger KaneAI Test Run
        id: trigger-test
        run: |
          response=$(curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
            --header 'accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic ${{ secrets.LT_KANEAI_AUTH }}' \
            --data '{
              "test_run_id": "${{ secrets.KANEAI_TEST_RUN_ID }}",
              "concurrency": 2,
              "title": "CI PR #${{ github.run_number }}",
              "region": "centralindia",
              "tunnel": "kaneai-local",
              "accessibility": false,
              "replaced_url": [
                {
                  "pattern_url": "https://staging.example.com",
                  "replacement_url": "http://localhost:5173"
                }
              ]
            }')

          echo "$response"
          job_id=$(echo $response | jq -r '.job_id')
          echo "Triggered Job ID: $job_id"
          echo "::set-output name=job_id::$job_id"

      - name: ✅ Confirm Job Triggered
        run: echo "Triggered KaneAI job ID: ${{ steps.trigger-test.outputs.job_id }}"